// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200612172811_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Species")
                        .IsRequired();

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            Description = "Very boop-able. Loves bellyrubs.",
                            Gender = "Female",
                            ImageUrl = "https://www.rover.com/blog/wp-content/uploads/2019/09/funny-cat-960x540.jpg",
                            Name = "Jennifur",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Description = "A prince among floofs. He only eats organic free-range waygu beef. Requires nightly brushing",
                            Gender = "Male",
                            ImageUrl = "https://www.wallpaperflare.com/static/98/704/904/white-brown-teacup-pomeranian-wallpaper-preview.jpg",
                            Name = "Chanteclaire",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 42,
                            Description = "Yes THAT Garfield. Retired hollywood cat looking for a fresh start. Loves Lazagna, hates mondays and requires diabetic medication.",
                            Gender = "Male",
                            ImageUrl = "https://i.redd.it/hq4is2vxe4y21.jpg",
                            Name = "Garfield",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 14,
                            Description = "Looks like a butthead but he's a big ol' softy once you get to know him.",
                            Gender = "Male",
                            ImageUrl = "https://i.imgur.com/x9K5JYo.jpg",
                            Name = "Mr.Grump",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            Description = "True to her name this gal literally can't stop smiling. Gluten Free",
                            Gender = "Female",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQKbCHEc_uRla-QRmnDse9ktweLdkE1C8c2_hD_rD_9MFTKQJKT&usqp=CAU",
                            Name = "Smiley",
                            Species = "Dog"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "test",
                            Username = "Tyler"
                        },
                        new
                        {
                            Id = 2,
                            Password = "itsyou",
                            Username = "MyFavoriteInstructor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
